apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dso-demo-java-secrets
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:WwJjjoWx/Ltp7MOmK5x6KiDmCtNf,iv:MCnUggFTtB/x5I21Twh5A7Ppyh9Xmka/bwY78cFdiI0=,tag:3tqACxv2xJ26pUvIOX9wIA==,type:str]
          labels:
            label1: ENC[AES256_GCM,data:pJPPTQ==,iv:NWxe6DGqxJJ+iMUIGjy/EqnFIXRfEOpG58YYGi09ARE=,tag:XdSoFzDyHBxEKQ+BqwKDZw==,type:str]
          annotations:
            key1: ENC[AES256_GCM,data:8HIDtw==,iv:/jyJduKomNaX0ECPwIEMackvGFg6Yn9kAE+tVTvjk/Y=,tag:/kezehf6Pi2FZlbq1B3TVA==,type:str]
          data:
            SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:gWLYKWQE7gqDD1WZkodsVA==,iv:1dW+NPcyUFn36abQL+LxdFB/PtsGQHhRba8zlWg/kBU=,tag:o5Me81debUEFhuwVTZ5Ruw==,type:str]
            PG_PASSWORD: ENC[AES256_GCM,data:zXjQ0Gmp2ZG2tyi1w+mLvyr+B70=,iv:pyLIcwwakkGUNBU6CPOK1/97lrCgWyaN69DeP7oCWw0=,tag:vPy5KPHTS7OG0EN6S+8eLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTFpvMDcwTGU3ZVp1WXZm
            eW5jRFhUMit5T1NrUEtwbGpoK0RHRFRDNzFjCjQwN0NrTitVWHZ6dHZBc0tNQ3pT
            M216bHBwUVdDbXZHbUE2T2lBUHZHbVkKLS0tIGRPTStzd0tTTS9DdFNGUUNiSDFO
            UmlYeUFRN28xVWh5OUZEcmR2VDlZakUKFeAAERlmA7G2IsaA6NqCt8IvlUtObZT4
            ywYvlmIgDNHNkutEXb6kindQK7wktYhyawgGjZeAovlUGdNYUV1wIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T21:44:18Z"
    mac: ENC[AES256_GCM,data:xqy5tD9cV0QgaTP03D+ovqyubkAlyOF7SWRyqTmx9i1VNatoK9PhLaN9P1ZnS7Xa9ELiZF7P78SMahv0yzhxf8TWTA5n5lZQXE8QP29iwRuaJ7ZuerV+rAQNHyrIDlWIgrzZNDSc3RRzHeflzrG0mq4gJPdsPvdt8JhMWvPf3dE=,iv:ZRhz2KqgbMamFXQ8/ceBitARUT56qfJHsNxr3K1po/E=,tag:pkiHdACsJbDyvH8F8Lp1Mg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.7.3
